package textAdventure;
import java.sql.*;
import java.util.ArrayList;

import org.apache.derby.jdbc.EmbeddedDataSource;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

//Holds schema and inserts for database
public class Database {

	/*
	 * Fields for the database instance
	 */
	private static String databaseURL;
	final static Logger log = LogManager.getLogger("LoggingExample");
	
	/*
	 * Method to run database creation
	 */
	public static void createGameDatabaseSchema() {
		//Create a GameManagement object
		GameManagement game = new GameManagement();
		
		//Try catch block for database transactions
		try {
			//Make a connection
			EmbeddedDataSource ds = new EmbeddedDataSource();
			ds.setDatabaseName("Game_Database");
			Connection conn = ds.getConnection();
			
			//Drop existing tables
			unloadTables(conn);
			
			//Create statments for each table
			Statement createItemSchema = conn.createStatement();
			Statement createRoomSchema = conn.createStatement();
			Statement createInteractableSchema = conn.createStatement();
			
			//Assing updates to those statments
			createItemSchema.executeUpdate("CREATE TABLE Items (id INT PRIMARY KEY, name varchar(50), description varchar(250), lore varchar(250), action varchar(100))");
			createRoomSchema.executeUpdate("CREATE TABLE Rooms (id INT PRIMARY KEY, name varchar(50), description varchar(250))");
			createInteractableSchema.executeUpdate("CREATE TABLE Interactables (id INT PRIMARY KEY, name varchar(50), description varchar(250), lore varchar(250), type varchar(50))");
			
			//Log successful database creation
			log.info("Database created successfully!");
			
			//Create entries for each table
			createItemEntries(conn);
			createInteractableEntries(conn);
			createRoomEntries(conn);
			
			//Create lists to hold rooms, items, and interactables generated by the loading methods
			ArrayList<Room> gameRooms = new ArrayList<Room>();
			ArrayList<Item> gameItems = new ArrayList<Item>();
			ArrayList<BaseInteractable> gameInteractables = new ArrayList<BaseInteractable>();
			
			//Load each tables data, and create the necessary objects
			loadRooms(conn, gameRooms);
			loadItems(conn, gameItems);
			
			
			//Map items and interactables to specific rooms
			
			
			//Set the lists of rooms, items, and interactables generated by the database to the game object lists
			
			
			//Close connection
			conn.close();
			
		} catch (SQLException e) {
			//Print errors
			log.error("There seems to have been an issue with the derby database, please try again.");
			e.printStackTrace();
		}
		
	}
	
	/*
	 * Methods to create entries in each table
	 */
	//Item entries
	public static void createItemEntries(Connection conn) {

		//Try catch block for database transactions
		try {
			//Use the connection to make some statements
			Statement itemEntryStatement = conn.createStatement();
			itemEntryStatement.executeUpdate("SQL INSERT STATEMENTS FOR ITEMS");
			
		} catch (SQLException e) {
			//Print errors
			log.error("There seems to have been an issue with the derby database, please try again.");
			e.printStackTrace();
		}
		
	}
	
	//Interactable entries
	public static void createInteractableEntries(Connection conn) {

		//Try catch block for database transactions
		try {
			//Use the connection to make some statements
			Statement interactableEntryStatement = conn.createStatement();
			interactableEntryStatement.executeUpdate("SQL INSERT STATEMENTS FOR INTERACTABLES");
			
		} catch (SQLException e) {
			//Print errors
			log.error("There seems to have been an issue with the derby database, please try again.");
			e.printStackTrace();
		}
		
	}
	
	//Room entries
	public static void createRoomEntries(Connection conn) {

		//Try catch block for database transactions
		try {
			//Use the connection to make some statements
			Statement roomEntryStatement = conn.createStatement();
			roomEntryStatement.executeUpdate("SQL INSERT STATEMENTS FOR ROOMS");
			
		} catch (SQLException e) {
			//Print errors
			log.error("There seems to have been an issue with the derby database, please try again.");
			e.printStackTrace();
		}
		
	}
	
	/*
	 * Loader methods for the database into creating objects in Java
	 */
	//Load rooms
	public static void loadRooms(Connection conn, ArrayList<Room> roomList) {
		
		//Try-catch
		try {
			//Use connection
			Statement loadRoom = conn.createStatement();
			ResultSet rooms = loadRoom.executeQuery("SELECT id, name, description FROM Rooms");
			
			//While there are rooms in the result set
			while(rooms.next()) {
				//Assign room fields to variables and create a room object
				int id = rooms.getInt("id");
				String name = rooms.getString("name");
				String desc = rooms.getString("description");
				
				Room room = new Room(name, desc, id);
				
				//Add the room to the list
				roomList.add(room);
			}
			
		} catch (SQLException e) {
			//Print errors
			log.error("There seems to have been an issue with the derby database, please try again.");
			e.printStackTrace();
		}
	}
	
	//Load items
	public static void loadItems(Connection conn, ArrayList<Item> itemList) {
		
		//Try-catch
		try {
			//Use connection
			Statement loadItem = conn.createStatement();
			ResultSet items = loadItem.executeQuery("SELECT id, name, description, lore, action FROM Items");
			
			//While there are rooms in the result set
			while(items.next()) {
				//Assign room fields to variables and create a room object
				int id = items.getInt("id");
				String name = items.getString("name");
				String desc = items.getString("description");
				String lore = items.getString("lore");
				String action = items.getString("action");
				
				Item item = new Item(name, id, desc, lore, action);
				
				//Add the room to the list
				itemList.add(item);
			}
			
		} catch (SQLException e) {
			//Print errors
			log.error("There seems to have been an issue with the derby database, please try again.");
			e.printStackTrace();
		}
	}
	
	//Load interactables
		public static void loadInteractables(Connection conn, ArrayList<BaseInteractable> interactableList) {
			
			//Try-catch
			try {
				//Use connection
				Statement loadInter = conn.createStatement();
				ResultSet interactables = loadInter.executeQuery("SELECT id, name, description, lore, type FROM Interactables");
				
				//While there are rooms in the result set
				while(interactables.next()) {
					//Assign room fields to variables and create a room object
					int id = interactables.getInt("id");
					String name = interactables.getString("name");
					String desc = interactables.getString("description");
					String lore = interactables.getString("lore");
					String type = interactables.getString("type");
					
					switch(type) {
					case "door":
						//Create a new door & add it to the list
						Door door = new Door(id, name, desc, lore);
						interactableList.add(door);
						break;
						
					case "pedestal":
						//Create a new pedestal & add it to the list
						Pedestal pedestal = new Pedestal(id, name, desc, lore);
						interactableList.add(pedestal);
						break;

					case "engraved-rock":
						//Create a new rock & add it to the list
						EngravedRock rock = new EngravedRock(id, name, desc, lore);
						interactableList.add(rock);
						break;

					}
					
				}
				
			} catch (SQLException e) {
				//Print errors
				log.error("There seems to have been an issue with the derby database, please try again.");
				e.printStackTrace();
			}
		}
	
	/*
	 * Drop tables method
	 */
	private static void unloadTables(Connection conn) {
		//Try-catch block
		try {
			//Drop the tables from the database
			Statement dropTableStatement = conn.createStatement();
			dropTableStatement.executeUpdate("DROP TABLE Items; DROP TABLE Rooms; DROP TABLE Interactables;");
			
		} catch (Exception e) {
			//Log out a message 
			log.warn("There was no table to drop");
		}
		
		log.info("Existing tables have been dropped.");
	}
	
	/*
	 * Mapping methods items and interactables
	 */
	
	
	/*
	 * Getters and setters for the database url
	 */
	public static String getURL() {
		return databaseURL;
	}
	
	public static void setURL(String url) {
		databaseURL = url;
	}
}
